on:
  workflow_call:
    inputs:
      no-cache:
        type: boolean
        required: false
        default: false

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "no-cache: ${{ inputs.no-cache }}"
      - name: Docker Build
        run: docker build . -f Dockerfile -t test:latest ${{ inputs.no-cache && '--no-cache' || '' }}
      - name: Delete
        run: docker rmi test:latest
